FILES=README tcping.c Makefile LICENSE
VERNUM=`grep VERSION tcping.c | cut -d" " -f3`
VER=tcping-$(VERNUM)

CCFLAGS=-Wall
#CC=gcc
CC=x86_64-w64-mingw32-gcc
LFLAGS = -lws2_32 -lwsock32


all: tcping.c
	$(CC) -o tcping $(CCFLAGS) -DHAVE_HSTRERROR tcping.c $(LFLAGS)

clean:
	rm -f tcping.solaris* tcping core *.o

